### ISSUE TITLE
Add the ability to specify multiple specification files/scenarios with maven

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-maven-plugin#12]
The following command works for single specs dir/file. But there is no way to specify multiple dirs/files using -DspecDir flag.

```
mvn gauge:execute -DspecsDir=specs/example.spec
```

**Comment by bkim54** [comment]
+1 this would be nice because gauge provides this feature

**Comment by mahendrakariya** [comment]
Fix should be available in plugin v1.2.0

**Comment by sguptatw** [comment]
@mahendrakariya : what would be the syntax? Should we also consider updating the documentation for this?

**Comment by mahendrakariya** [comment]
Multiple specs dir should be separated by spaces, the same as you do for `gauge` command on console.
```
<specsDir>specs1 specs2 specs3/foo.spec</specsDir>
```
