### ISSUE TITLE
-Dspecs tag is not being considered

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-maven-plugin#14]
In a maven project even though the directory specified using -Dspecs all the specs are getting executed.

**Version**
```
Gauge version: 0.8.1.nightly-2017-02-23

Plugins
-------
html-report (3.1.0)
java (0.6.1.nightly-2017-02-23)
```

**Comment by kashishm** [comment]
@sguptatw It's `-DspecsDir` and not `-Dspecs`. Here's the link to [doc](https://docs.getgauge.io/configuration.html#to-only-run-gauge-specs)

**Comment by sguptatw** [comment]
Yes I got confused because of the space in the docs

**Comment by kashishm** [comment]
@sguptatw It's how the search highlight works.
