### ISSUE TITLE
Travis builds are failing even when the Build state is successful

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-maven-plugin#19]
**Expected behavior**
Build should pass when build state is successful.

**Actual behavior**
https://travis-ci.org/getgauge/gauge-java is failing even when the Build state is successful

**Notes**
appveyor build is also failing, this is because of the maven plugin
it doesnt use the latest gauge syntax
so the [DEPRECATED] messages are written to STDERR, causing the builds to note it as failure.

**Version**
```
gauge-maven-plugin 1.1.0
```

**Comment by kashishm** [comment]
This issue is fixed. This was happening because the messages were printing on stderr but we have changed it to print on stdout.
