### ISSUE TITLE
Re-run via gauge-maven plugin doesn't work

### ISSUE THREAD

**Issue by olejkavn** [getgauge/gauge-maven-plugin#24]
Gauge version: 0.9.1

Plugins
-------
html-report (4.0.2)
java (0.6.4)
spectacle (0.1.2)
xml-report (0.2.0)

mvn goal:
```
mvn gauge:execute -DspecsDir=specs -Dflags=--failed
```
result:
```
Rerun is not supported via the old usage. Use 'gauge run -f'
```

**Comment by BugDiver** [comment]
rerunning failed tests are available in latest release. Failed tests can be executed by issuing command `mvn clean test -Dflags="-f"`.

**Comment by olejkavn** [comment]
@BugDiver maybe you have some advise:

mvn gauge:execute -Dtags=SomeTag
and next step
mvn gauge:execute -Dflags="-f"

from console: rerun failed tests of SomeTag tag
from TeamCity:run of all tests of specs directory

how I can rerun tests from TC?

NOTE: In TeamCity each goal is separate build step

**Comment by sriv** [comment]
@olejkavn - gauge stores the previous run information in the `.gauge` folder of your project. `rerun` command uses the contents of this folder to trigger the next run.

My guess is that in your case, the artifacts between each goal are not shared, hence the state of the last run is not available to the new goal (which triggers `rerun`). 

If you need this, you may try sharing the `.gauge` folder as a build artifact and propagate it to the new goal.
