### ISSUE TITLE
Add ability to run a single test scenario

### ISSUE THREAD

**Issue by chrisnappin** [getgauge/gauge-maven-plugin#27]
Please can you add the ability to run a single test scenario? This makes working on writing tests in a large testsuite much easier!

Note: as I'm using this plugin and the maven-failsafe-plugin plugin to organise my Gauge test framework code into ```src/main``` (so I can have tests for the tests under ```src/test```), I can no longer use the ```gauge``` binary to directly run tests, passing the scenario file and line number.

Passing the scenario file and line number as a command line parameter or plugin config setting, like **env** and **tags**, would be really useful?

**Comment by sriv** [comment]
You can run a single scenario by passing it using the `specsDir` flag.

Example:

```
gauge init java_maven
mvn test-compile gauge:execute -DspecsDir=specs\example.spec:16
```

**Comment by chrisnappin** [comment]
Ah, thanks. I had tried that and it didn't work, but I've now found that was because I had specsDir defined in my pom.xml too, as per the example config. 

I guess it would be helpful if command line properties override any in the Maven configuration?

**Comment by chrisnappin** [comment]
Original issue resolved (would be grateful if you could take the command line property override suggestion though!)

**Comment by emirhangl** [comment]
@chrisnappin Thanks man, finally got the solution.
