### ISSUE TITLE
Allow to run single specification/scenario

### ISSUE THREAD

**Issue by tlempart** [getgauge/gauge-maven-plugin#3]
According to http://getgauge.io/documentation/user/current/execution/README.html there is possibility to run single specification or even scenario with `gauge` command. I don't see such possibility in case of maven plugin, so it is either not documented or not possible.

**Comment by tlempart** [comment]
Somehow it is possible to run single specification(s) using parameter `specsDir`, but there is no clear information, that it can be used this way (at least link to execution chapter). Additionally this parameter does not work for single scenario execution, i.e. when I specify wrong line, than I get:
```
[INFO] No specifications found.
```
btw. should it be at least warning? When I specify correct one, than I get again `No specifications found`.

**Comment by prateekbaheti** [comment]
The specsDir parameter can be used to execute a single specification, for
example set to *specs/hello_world.spec:0 *if you want to run the first
spec. The number value indicates the index of the scenario you want to
execute. 0 for the first scenario, 1 for the second and so on. We need to
improve the documentation on this usage, thanks for pointing that out.

The warning message could be improved, I agree because it doesn't mention
the cause for not finding any specs.

Thanks,
Prateek

**Comment by tSundaram** [comment]
Step1: Install Gauge in your windows
Step2: Add Gauge VS 2013 in Visual Studio Extensions
Step 3: Update Gauge library in nuget packages
Step 4: Check in command line whether you have csharp plugin installed ** "gauge -v"**
if not, then install csharp plugin  **"gauge --install csharp"**
Steps5: **"gauge --init csharp"**

Once you initiated csharp then you will see this in commnadline

**gauge --init csharp**

```
13:07:03.653 [INFO]  create  manifest.json
13:07:03.656 [INFO]  create  specs
13:07:03.658 [INFO]  create  specs/hello_world.spec
13:07:03.672 [INFO]  create  env
13:07:03.674 [INFO]  create  env/default
13:07:03.677 [INFO]  create  env/default/default.properties
install create  Specs
install create  Properties\AssemblyInfo.cs
install create  StepImplementation.cs
install create  packages.config
install create  Specs.csproj
install create  Specs.sln
install Installing Nuget Package : Gauge.CSharp.Lib, version: 0.5.2.0
install Done Installing Nuget Package!
13:07:06.771 [INFO]
Successfully initialized the project. Run specifications with "gauge specs/" 
```

then 
Step6:
run your specs using **"gauge specs/yourspec.spec"**

**Comment by testLab3** [comment]
Hi prateekbaheti ,

It does not work for me... 
Seems to be a nice tool, but having that kind of problem in the beginning may affect my decision about using it the future...

![capture](https://cloud.githubusercontent.com/assets/23270075/20025743/d29238e2-a2ae-11e6-9fcc-cc1a8ea96fb4.PNG)

**Comment by sriv** [comment]
hi @testLab3 - I am assuming that you are using a newer version of gauge. If so there is a change in the way you could run a single scenario.

Gauge now requires you to give the line number of the scenario that you want to execute, and not the index. Please read more [here](http://getgauge.io/documentation/user/current/advanced_readings/execution_types/#single-scenario-execution).

**Comment by testLab3** [comment]
Hi Srikanth,

I've got another problem, which have never had with other frameworks.

After creating a simple Gauge project in IntelliJ ADEA.(not using Maven) I
got the following result...

My script:

import com.thoughtworks.gauge.Step;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class MyTest {

    private static WebDriver driver;

    @Step("Open the application")
    public void newTest() throws InterruptedException {
        driver = new FirefoxDriver();
        driver.get("https://google.com");
        Thread.sleep(3000);
        driver.close();

    }

}


My result:

C:\_Work\Dev\TestAutomation\MyNewTEST\src\test\java>javac -Xlint MyTest.java
MyTest.java:1: error: package com.thoughtworks.gauge does not exist
import com.thoughtworks.gauge.Step;
                             ^
MyTest.java:2: error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebDriver;
                          ^
MyTest.java:3: error: package org.openqa.selenium.firefox does not exist
import org.openqa.selenium.firefox.FirefoxDriver;
                                  ^
MyTest.java:7: error: cannot find symbol
    private static WebDriver driver;
                   ^
  symbol:   class WebDriver
  location: class MyTest
MyTest.java:9: error: cannot find symbol
    @Step("Open the application")
     ^
  symbol:   class Step
  location: class MyTest
MyTest.java:11: error: cannot find symbol
        driver = new FirefoxDriver();
                     ^
  symbol:   class FirefoxDriver
  location: class MyTest
6 errors



As you can see, all jars are imported successfully, but when I run my test
it says "package xxxxx does not exist"...

Could you please explain what is wrong here?

Thanks

**Comment by kashishm** [comment]
@testLab3 The above errors are shown because `gauge-java` and `selenium` dependencies are not in classpath.
Here's the [documentation](http://getgauge.io/documentation/user/current/ide_support/features.html#execution) on how to run specs in IntelliJ.

**Comment by testLab3** [comment]
If I run all or individual spec from IntelliJ it works perfectly fine
without setting any dependencies.  But if run it from the Terminal I get
this error.
The documentation, you are referring to, shows how to create a project. I
doesn't say how to properly add external jars. In order to do that I'm
following steps which IntelliJ recommends in this case.

So my question is: How to add external jars?

Thank you

**Comment by testLab3** [comment]
There is a typo in the previous message I meant "It doesn't say how to
properly add external jars to a Gauge project"

Thanks

**Comment by kashishm** [comment]
Run `gauge <path_to_specs_dir>` in your gauge project to run specs from command line. When running via the CLI, you need to set [GAUGE_ADDITIONAL_LIBS](http://getgauge.io/documentation/user/current/language_features/configuration.html#gaugeadditionallibs) env var to the location of the jars. If the location is pre-determined and consistent across machines/environments, you could include this setting in your project's env/{env}/{any}.properties

The Intellij plugin does this automatically. Hence you might see this working via Intellij+Gauge.

**Comment by testLab3** [comment]
I'm sorry it didn't work for me... It runs both in Terminal and in CLI but
with errors.

Here is what I'm getting...

C:\_Work\Dev\TestAutomation\T1>gauge specs\Login.spec
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
# Specification Heading
  ## Scenario Heading    P

**Comment by jiglesiasromero** [comment]
I have the same error as @testLab3

`src/test/java/DataGetter/JSonManager.java:23: error: cannot find symbol
    private DocumentContext context=null;
            ^
  symbol:   class DocumentContext
  location: class JSonManager
src/test/java/DataGetter/JSonManager.java:24: error: cannot find symbol
    private Configuration configuration;
            ^
  symbol:   class Configuration
  location: class JSonManager
src/test/java/DataGetter/JSonManager.java:26: error: cannot find symbol
    public JSonManager() throws AppException {
                                ^
  symbol:   class AppException
  location: class JSonManager
src/test/java/DataGetter/JSonManager.java:31: error: cannot find symbol
    public JSonManager(String file) throws AppException{
                                           ^
  symbol:   class AppException
  location: class JSonManager
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:7: error: package com.jayway.jsonpath does not exist
import com.jayway.jsonpath.Configuration;
                          ^
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:8: error: package com.jayway.jsonpath does not exist
import com.jayway.jsonpath.DocumentContext;
                          ^
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:9: error: package com.jayway.jsonpath does not exist
import com.jayway.jsonpath.JsonPath;
                          ^
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:10: error: package com.jayway.jsonpath.spi.json does not exist
import com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider;
                                   ^
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:11: error: package com.jayway.jsonpath.spi.mapper does not exist
import com.jayway.jsonpath.spi.mapper.JacksonMappingProvider;
                                     ^
src/test/java/DataGetter/JSonManagerChangeJsonParam.java:12: error: package tools.coretools does not exist
import tools.coretools.AppException;
                      ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
process /usr/lib/jvm/java-8-oracle/bin/javac with pid 10076 quit unexpectedly. exit status 1
Failed to start gauge API: Runner with pid 10071 quit unexpectedly(exit status 1).`

**Comment by virendrarawat** [comment]
Has this issue been resolve. I am getting below error if i run spec from command prompt;
error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebDriver;
                          ^
From intellij it works fine.

**Comment by Apoorva-GA** [comment]
@virendrarawat When running via the command line, you need to set [gauge_additional_libs](https://docs.gauge.org/latest/configuration.html#language-plugin) env var to the location of the jars. 
Intellij plugin does this automatically. Hence you see this working via Intellij+Gauge.

Let us know if this works for you.

**Comment by Apoorva-GA** [comment]
Are you getting `Step implementation not found` errors for implemented steps? If not you will have to add the implementation for the unimplemented steps.

But anyway the execution of implemented steps should continue after the validation error.

**Comment by virendrarawat** [comment]
@Apoorva-GA , I have added the steps, its working fine if i run from intellij. This error comes only when i run from command prompt.
you are right, execution continued after the validation error.
        }
Successfully generated html-report to => C:\i2iSimplifyAutomation\reports\html-report\index.html
Specifications: 0 executed      0 passed        0 failed        1 skipped
Scenarios:      0 executed      0 passed        0 failed        2 skipped

Total time taken: 256ms
Any suggession how can i resolved validation error
