### ISSUE TITLE
Rerun flag broken

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-maven-plugin#30]
_From @olejkavn on May 23, 2018 8:50_

### Expected behavior
rerun works fine

 with maven plugin

### Actual behavior
rerun doesn't work

### Steps to reproduce
sample project: [ioc-spring-master.zip](https://github.com/getgauge/gauge/files/2030229/ioc-spring-master.zip)
1.mvn clean install
2.mvn gauge:execute
3.mvn gauge:execute -Dflags="f"

### Gauge version
```
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
java (0.6.7)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

### Maven version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: C:\apache-maven-3.5.5\bin\..
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Java\jdk1.8.0_131\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

_Copied from original issue: getgauge/gauge#1051_

**Comment by sguptatw** [comment]
_From @zabil on May 23, 2018 9:2_

Refer discussion on Gitter [May 23, 2018 2:12 PM](https://gitter.im/getgauge/chat?at=5b05298baaafa25932abf87b)

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge and gauge-maven-plugin nightly >= 24/05/18

**Comment by sguptatw** [comment]
Released

**Version**
Gauge version: 1.0.0
gauge-maven-plugin: 1.3.3

**Comment by sguptatw** [comment]
Observed on
```
Gauge version: 1.0.3.nightly-2018-10-05
Commit Hash: ff2114f
gauge-maven-plugin: 1.3.3
```

**Steps to replicate**
* Run gauge-tests https://github.com/getgauge/gauge-tests
* `mvn gauge:execute -Dflags="--repeat"`
> Observed same behavior `mvn gauge:execute -Dflags="--failed"`

**Comment by sguptatw** [comment]
Verified with version `1.4.0-nightly-2018-10-18`

* Add following lines in `pom.xml`
```xml
    <pluginRepositories>
        <pluginRepository>
            <id>gauge-maven-plugin</id>
            <url>https://dl.bintray.com/gauge/gauge-maven-plugin</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```

* Update the version to nightly 
```xml
            <plugin>
                <groupId>com.thoughtworks.gauge.maven</groupId>
                <artifactId>gauge-maven-plugin</artifactId>
                <version>1.4.0-nightly-2018-10-18</version>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <configuration combine.self="override">
                            <specsDir>specs</specsDir>
                            <inParallel>${inParallel}</inParallel>
                        </configuration>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
