### ISSUE TITLE
Respect -DskipTests parameter 

### ISSUE THREAD

**Issue by NeoScaler** [getgauge/gauge-maven-plugin#36]
We use Gauge in a multi module setup and it gets built also on servers where Gauge isn't available. There we do not want to execute any tests.

It would be handy if the Gauge plugin would respect the Maven parameters -DksipTests and/or -Dmaven.test.skip=true, so that it does not do anything nor require Gauge to installed.

So you could execute a "mvn install -DskipTests" in the parent POM for example without Gauge.

**Comment by segeli** [comment]
@nehashri It should be defined in mojo with some similar parameters. These parameters map skipTests and maven.test.skip. 

We can verify parameters and if not verified before execution, then we can break it.

**Comment by nehashri** [comment]
@segeli Yes that is one way to do this.

**Comment by nehashri** [comment]
Should be fixed with commit https://github.com/getgauge/gauge-maven-plugin/commit/4eec7182e776a1403631b0b55e36ec5b1d1a01a4

**Comment by 7Bit** [comment]
Thanks for the fast implementation, going to test it as soon as it is released.

**Comment by 7Bit** [comment]
Tested it using release version 1.3.4. Works like a charm, thanks a lot.

**Comment by sguptatw** [comment]
Getting error
```
Plugin com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.4 or one of its dependencies could not be resolved: Failure to find com.thoughtworks.gauge.maven:gauge-maven-plugin:jar:1.3.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
**Steps to replicate**
* Create a java_maven project
* Update the pom to use gauge-maven-plugin:1.3.4
```
            <plugin>
                <groupId>com.thoughtworks.gauge.maven</groupId>
                <artifactId>gauge-maven-plugin</artifactId>
                <version>1.3.4</version>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <configuration>
                            <specsDir>specs</specsDir>
                        </configuration>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
> Run the maven project `mvn clean test`. The above error can be observed.

**Comment by NeoScaler** [comment]
> Getting error
> 
> ```
> Plugin com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.4 or one of its dependencies could not be resolved: Failure to find com.thoughtworks.gauge.maven:gauge-maven-plugin:jar:1.3.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
> ```
> > Run the maven project `mvn clean test`. The above error can be observed.

Must be some kind of local error on your side, because it is definitely present in Maven Central:
https://search.maven.org/artifact/com.thoughtworks.gauge.maven/gauge-maven-plugin/1.3.4/maven-plugin

Update in POM also worked for me yesterday.

**Comment by BugDiver** [comment]
Works as expected with version 1.3.4
