### ISSUE TITLE
New Gauge Maven project in intellij doesn't find implementations.

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-maven-plugin#4]
Intellij doesn't recognize the project as gauge project, So intellij doesn't start Gauge API.

Workaround : Reopen the project.

**Comment by sguptatw** [comment]
Tested with
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
java (0.6.9.nightly-2018-06-06)
```
Gauge-IntelliJ - 0.3.11.nightly-2018-05-10

On Using the latest archetypes to create a project, the Gauge steps are recongnized and navigation is working as expected. However run has an issue tracked in https://github.com/getgauge/Intellij-Plugin/issues/335
