### ISSUE TITLE
to support table-rows property natively instead of as a flag.

### ISSUE THREAD

**Issue by chaithu-gauge** [getgauge/gauge-maven-plugin#48]
mvn test-compile gauge:execute -DspecsDir=specs/x.spec -Dflags="--table-rows=1,3",The problem with this it will run only the 3rd row, coz the table-rows flag will be overriden.
So as I said currently there is know way to achieve --table-rows=1,2,3 feature

**Comment by negiDharmendra** [comment]
@chaithu-gauge If you want to execute continues rows then this `-Dflags="--table-rows=1-3"` should help you.

**Comment by Apoorva-GA** [comment]
Closing this for now. Feel free to get back if you have any other questions.
