### ISSUE TITLE
Release Tasks  1.4.0

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-maven-plugin#49]
These are the release activities to be performed when releasing Gauge-Maven-Plugin.
## Pre release
- [x] Check all commits that has been added with this release and make sure the relevant issues are tested/closed.
- [x] Check if all relevant tests are passing.
- [x] Take a call on release.

## Release
- [x] Trigger the maven release stages.

## Post release
- [x] Check the released version is available in maven central.
- [x] Send release mail to google groups.
- [x] Bump up version for further development

**Comment by haroon-sheikh** [comment]
@Apoorva-GA @BugDiver The plugin was released with java 10.
We should release the current version with java 8 first and then move onto java 10 and release v2.0.0 of the plugin. Here's the revert to java8 https://github.com/getgauge/gauge-maven-plugin/pull/51

**Comment by nehashri** [comment]
@haroon-sheikh Unfortunately, the plugin has been released already. I don't think a revert would be helpful here. Also, since Java 8 is soon to be deprecated, we don't plan on supporting it anymore.

**Comment by haroon-sheikh** [comment]
@nehashri Think we should release a patch with java8.

**Comment by BugDiver** [comment]
@haroon-sheikh The team has decided to make a patch release with Java 8 support. We will try to get it working with Java 8 and 10 both.

**Comment by BugDiver** [comment]
@haroon-sheikh  the PR #51 has been merged. We will be making a release soon. Please refer #52
