### ISSUE TITLE
should do test-compile along with compile

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-maven-plugin#8]
When running tests with maven, currently, it only does a compile of the main java sources not the test sources.

We have to do `mvn test-compile` before I can use `mvn gauge:execute -DspecsDir=specs` otherwise it throws up step implementation not found.

**Comment by deepthigc** [comment]
Thanks @haroon-sheikh. Would you like to submit a pull request for what you've done? We can take a quick look and merge it? How do you feel about that? We would love to have more contribution.
