### ISSUE TITLE
Should default to run in project.basedir

### ISSUE THREAD

**Issue by bentatham** [getgauge/gauge-maven-plugin#9]
In order to work nicely in multi-module projects, gauge should be run in the project.basedir by default, and perhaps add a configuration option for ``--dir``.

**Comment by mahendrakariya** [comment]
Can you try passing the directory in `-Dflags`?

**Comment by bentatham** [comment]
Yes, using ``-Dflags`` or adding it in ``<flags><flag>--dir=${project.basedir}</flag></flags>`` works.  But it seems to be me this should be the default to work with Maven, in general.  I can't think of a case you would _not_ want that, as it does not change the behaviour a single-module project.

**Comment by mahendrakariya** [comment]
I think what you are saying makes sense. We will take it as a feature request. It would be great if you could outline your project structure here. We can refer it as a real example.

In the meanwhile, if you would like to take a stab at it, feel free to submit a pull request.

**Comment by bentatham** [comment]
I'm already working on a PR. 

In my case, I wanted to separate the gauge tests into its own module from the application itself.  That way, I can deploy the final deliverable from the application module and then run gauge tests against it.  In theory, I could use the ``integration-test`` phases of maven, but I often find that too restrictive in terms of getting all the plugin binding I need into the maven lifecycle, and this allows us to play with gauge without affecting the primary module.  The directory structure is very simple:

 * parent-project
  * application-project
  * application-test-with-gauge

**Comment by mahendrakariya** [comment]
This issue has been resolved, thanks to the PR by @bentatham!!
